-- Blogfront Initial Database Schema
-- Based on standard ANSI SQL mapping from the original SQL Server schema

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Uuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Username NVARCHAR(100),
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    DisplayName NVARCHAR(255),
    Bio NVARCHAR(500),
    AvatarUrl NVARCHAR(500),
    Website NVARCHAR(500),
    Role NVARCHAR(50) DEFAULT 'Member',
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME,
    UpdatedAt DATETIME2(7) NOT NULL,
    Slug NVARCHAR(255),
    Status NVARCHAR(50),
    ProfileImage NVARCHAR(1000),
    CoverImage NVARCHAR(1000),
    Twitter NVARCHAR(255),
    Facebook NVARCHAR(255),
    LastLogin DATETIME2(7),
    MetaTitle NVARCHAR(255),
    MetaDescription NVARCHAR(MAX),
    CreatedByUserId UNIQUEIDENTIFIER
);

CREATE TABLE Categories (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Slug NVARCHAR(255) NOT NULL UNIQUE,
    AuthorId UNIQUEIDENTIFIER,
    FOREIGN KEY (AuthorId) REFERENCES Users(Id) ON DELETE SET NULL
);

CREATE TABLE Tags (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Slug NVARCHAR(255) NOT NULL UNIQUE,
    AuthorId UNIQUEIDENTIFIER,
    FOREIGN KEY (AuthorId) REFERENCES Users(Id) ON DELETE SET NULL
);

CREATE TABLE Posts (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Uuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Title NVARCHAR(255) NOT NULL,
    Slug NVARCHAR(255) NOT NULL UNIQUE,
    Type NVARCHAR(50),
    Status NVARCHAR(50),
    Visibility NVARCHAR(50),
    Html NVARCHAR(MAX),
    Plaintext NVARCHAR(MAX),
    FeatureImage NVARCHAR(1000),
    AllowComments BIT NOT NULL DEFAULT 1,
    ViewCount INT,
    ScheduledAt DATETIME2(7),
    PublishedAt DATETIME,
    CreatedAt DATETIME,
    UpdatedAt DATETIME,
    AuthorId UNIQUEIDENTIFIER,
    MetaTitle NVARCHAR(255),
    MetaDescription NVARCHAR(MAX),
    CanonicalUrl NVARCHAR(1000),
    OgImage NVARCHAR(1000),
    OgTitle NVARCHAR(255),
    OgDescription NVARCHAR(MAX),
    TwitterImage NVARCHAR(1000),
    TwitterTitle NVARCHAR(255),
    TwitterDescription NVARCHAR(MAX),
    FOREIGN KEY (AuthorId) REFERENCES Users(Id) ON DELETE SET NULL
);

CREATE TABLE Comments (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    PostId UNIQUEIDENTIFIER,
    ParentId UNIQUEIDENTIFIER,
    MemberId UNIQUEIDENTIFIER,
    AuthorName NVARCHAR(200) NOT NULL,
    AuthorEmail NVARCHAR(200) NOT NULL,
    AuthorUrl NVARCHAR(500),
    AuthorIp NVARCHAR(50),
    Content NVARCHAR(MAX) NOT NULL,
    Html NVARCHAR(MAX),
    Status NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME2(7) NOT NULL,
    FOREIGN KEY (PostId) REFERENCES Posts(Id) ON DELETE CASCADE,
    FOREIGN KEY (MemberId) REFERENCES Users(Id) ON DELETE NO ACTION,
    FOREIGN KEY (ParentId) REFERENCES Comments(Id) ON DELETE NO ACTION
);

CREATE TABLE Media (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    FileName NVARCHAR(255),
    OriginalFileName NVARCHAR(255),
    FilePath NVARCHAR(MAX),
    Url NVARCHAR(MAX) NOT NULL,
    ContentType NVARCHAR(100),
    FileSize BIGINT,
    Width INT,
    Height INT,
    AltText NVARCHAR(MAX),
    Caption NVARCHAR(MAX),
    UploadedBy UNIQUEIDENTIFIER,
    CreatedAt DATETIME,
    FOREIGN KEY (UploadedBy) REFERENCES Users(Id) ON DELETE SET NULL
);

CREATE TABLE Pages (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    ParentId UNIQUEIDENTIFIER,
    AuthorId UNIQUEIDENTIFIER,
    FeaturedImageId UNIQUEIDENTIFIER,
    Title NVARCHAR(255) NOT NULL,
    Slug NVARCHAR(255) NOT NULL UNIQUE,
    Content NVARCHAR(MAX),
    IsInNav BIT,
    SortOrder INT,
    IsPublished BIT NOT NULL DEFAULT 0,
    PublishedAt DATETIME2(7),
    CreatedAt DATETIME2(7) NOT NULL,
    UpdatedAt DATETIME2(7) NOT NULL,
    MetaTitle NVARCHAR(MAX),
    MetaDescription NVARCHAR(MAX),
    CanonicalUrl NVARCHAR(MAX),
    OgImage NVARCHAR(MAX),
    OgTitle NVARCHAR(MAX),
    OgDescription NVARCHAR(MAX),
    TwitterImage NVARCHAR(MAX),
    TwitterTitle NVARCHAR(MAX),
    TwitterDescription NVARCHAR(MAX),
    FOREIGN KEY (AuthorId) REFERENCES Users(Id) ON DELETE SET NULL,
    FOREIGN KEY (ParentId) REFERENCES Pages(Id) ON DELETE NO ACTION,
    FOREIGN KEY (FeaturedImageId) REFERENCES Media(Id) ON DELETE SET NULL
);

CREATE TABLE Settings (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId UNIQUEIDENTIFIER,
    JsonPayload NVARCHAR(MAX) NOT NULL,
    UpdatedAt DATETIME2(7) NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE CustomThemeSettings (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    SettingGroup NVARCHAR(100) NOT NULL DEFAULT 'general',
    SettingKey NVARCHAR(200) NOT NULL,
    SettingType NVARCHAR(50) NOT NULL DEFAULT 'text',
    SettingValue NVARCHAR(MAX),
    DefaultValue NVARCHAR(MAX),
    Label NVARCHAR(200),
    Description NVARCHAR(500),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Uuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX)
);

CREATE TABLE Permissions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Uuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Name NVARCHAR(255) NOT NULL,
    ActionType NVARCHAR(50) NOT NULL,
    ObjectType NVARCHAR(50) NOT NULL
);

CREATE TABLE PermissionsRoles (
    PermissionId UNIQUEIDENTIFIER NOT NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (PermissionId, RoleId),
    FOREIGN KEY (PermissionId) REFERENCES Permissions(Id) ON DELETE CASCADE,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE
);

CREATE TABLE RolesUsers (
    RoleId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (RoleId, UserId),
    FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE PostCategories (
    PostId UNIQUEIDENTIFIER NOT NULL,
    CategoryId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (PostId, CategoryId),
    FOREIGN KEY (PostId) REFERENCES Posts(Id) ON DELETE CASCADE,
    FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE CASCADE
);

CREATE TABLE PostTags (
    PostId UNIQUEIDENTIFIER NOT NULL,
    TagId UNIQUEIDENTIFIER NOT NULL,
    SortOrder INT,
    PRIMARY KEY (PostId, TagId),
    FOREIGN KEY (PostId) REFERENCES Posts(Id) ON DELETE CASCADE,
    FOREIGN KEY (TagId) REFERENCES Tags(Id) ON DELETE CASCADE
);

-- Note: Indexes on frequently searched columns (Slug, Status, AuthorId, etc.) are recommended
-- but omitted from this basic standard table creation script for universal compatibility.
