-- Drop obsolete token and security tracker columns from Users table
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Users' AND COLUMN_NAME='RefreshToken')
    ALTER TABLE Users DROP COLUMN RefreshToken;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Users' AND COLUMN_NAME='RefreshTokenExpiry')
    ALTER TABLE Users DROP COLUMN RefreshTokenExpiry;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Users' AND COLUMN_NAME='AccessFailedCount')
    ALTER TABLE Users DROP COLUMN AccessFailedCount;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Users' AND COLUMN_NAME='LockoutEnd')
    ALTER TABLE Users DROP COLUMN LockoutEnd;
